# RTC64 Sovereign OS - Limine Configuration

TIMEOUT=3
GRAPHICS=yes

:R-TECH Sovereign OS (Integrated Stable)
    PROTOCOL=limine
    KERNEL_PATH=boot:///boot/sys/kernel.elf
    COMMENT=Baking Real Bare-Metal Environment.

:R-TECH Sovereign OS (Debug Mode)
    PROTOCOL=limine
    KERNEL_PATH=boot:///boot/sys/kernel.elf
    KERNEL_CMDLINE=debug
    COMMENT=Verbose hardware discovery and stack traces.
