#ifndef USB_CONFIG_H
#define USB_CONFIG_H

#define CONFIG_USB_PRINTF printf
#define CONFIG_USBHOST_MAX_MSC_CLASS 1
#define CONFIG_USBHOST_MAX_HID_CLASS 1
#define CONFIG_USBHOST_MAX_VIDEO_CLASS 1
#define CONFIG_USBHOST_MAX_AUDIO_CLASS 1
#define CONFIG_USBHOST_MAX_CDC_ECM_CLASS 1
#define CONFIG_USBHOST_MAX_CDC_NCM_CLASS 1
#define CONFIG_USBHOST_MAX_ENDPOINTS 8
#define CONFIG_USBHOST_MSC_TIMEOUT 5000
#define CONFIG_USB_ALIGN_SIZE 64

#define CONFIG_USBHOST_DEV_NAMELEN 16
#define CONFIG_USBHOST_MAX_INTF_ALTSETTINGS 1
#define CONFIG_USBHOST_MAX_INTERFACES 1
#define CONFIG_USBHOST_MAX_EHPORTS 1
#define CONFIG_USBHOST_MAX_RHPORTS 1
#define CONFIG_USBHOST_MAX_EXTHUBS 1
#define CONFIG_USBHOST_PSC_STACKSIZE 2048
#define CONFIG_USBHOST_PSC_PRIO 4
#define CONFIG_USBHOST_REQUEST_BUFFER_LEN 256
#define CONFIG_USBHOST_CONTROL_TRANSFER_TIMEOUT 500

/* Host controller settings */
#define CONFIG_USBHOST_EHCI
#define CONFIG_USBHOST_MAX_BUS 1
#define CONFIG_USB_EHCI_HCCR_OFFSET 0
#define CONFIG_USB_EHCI_FRAME_LIST_SIZE 1024

/* Device controller settings (if needed by usbd_core) */
#define CONFIG_USBDEV_REQUEST_BUFFER_LEN 256
#define CONFIG_USBDEV_MAX_BUS 1

#define CONFIG_USBHOST_CDC_NCM_ETH_MAX_RX_SIZE (2048)
#define CONFIG_USBHOST_CDC_NCM_ETH_MAX_TX_SIZE (2048)

#define USB_NOCACHE_RAM_SECTION

#endif
