#ifndef USB_CONFIG_H
#define USB_CONFIG_H

#define CONFIG_USB_PRINTF printf
#define CONFIG_USBHOST_MAX_MSC_CLASS 1
#define CONFIG_USBHOST_MAX_HID_CLASS 1
#define CONFIG_USBHOST_MAX_ENDPOINTS 4
#define CONFIG_USBHOST_MSC_TIMEOUT 5000
#define CONFIG_USB_ALIGN_SIZE 64

#define CONFIG_USBHOST_DEV_NAMELEN 16
#define CONFIG_USBHOST_MAX_INTF_ALTSETTINGS 1
#define CONFIG_USBHOST_MAX_INTERFACES 1
#define CONFIG_USBHOST_MAX_EHPORTS 1
#define CONFIG_USBHOST_MAX_EXTHUBS 1
#define CONFIG_USBHOST_REQUEST_BUFFER_LEN 256
#define CONFIG_USBHOST_CONTROL_TRANSFER_TIMEOUT 500

/* Host controller settings */
#define CONFIG_USBHOST_EHCI
#define CONFIG_USBHOST_MAX_BUS 1
#define CONFIG_USB_EHCI_HCCR_OFFSET 0
#define CONFIG_USB_EHCI_FRAME_LIST_SIZE 1024

/* Device controller settings (if needed by usbd_core) */
#define CONFIG_USBDEV_REQUEST_BUFFER_LEN 256
#define CONFIG_USBDEV_MAX_BUS 1

#define USB_NOCACHE_RAM_SECTION
#define USB_MEM_ALIGNX __attribute__((aligned(64)))

#endif
