#define WOLFSSL_USER_SETTINGS
#include <pro_os.h>
#define WOLFSSL_GENERAL_ALIGNMENT 8
#define SINGLE_THREADED
#define NO_FILESYSTEM
#define NO_WRITEV
#define NO_DEV_RANDOM
#define USE_CERT_BUFFERS_2048
