#ifndef WOLFSSL_USER_SETTINGS_H
#define WOLFSSL_USER_SETTINGS_H
#define WOLFSSL_USER_IO
#define NO_FILESYSTEM
#define NO_WOLFSSL_DIR
#define NO_MAIN_DRIVER
#define WOLFSSL_64BIT_ADDR
#define SINGLE_THREADED
#define WOLFCRYPT_ONLY
#define NO_AES
#define NO_RSA
#define NO_SHA
#define NO_MD5
#define NO_HMAC
#define NO_PWDBASED
#define NO_ASN
#define NO_CODING
#define NO_CERTS
#define NO_SIG_WRAPPER
#define NO_DSA
#define NO_DH
#define NO_RC4
#define NO_DES3
#define NO_MD4
#define NO_SHA256
#define NO_CURVED25519
#define NO_ED25519
#define NO_CURVE448
#define NO_ED448
#define NO_ERROR_STRINGS
#endif
